# Docker Compose override for local development
# This file is automatically loaded by docker-compose and overrides docker-compose.yml

version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount source code for development
      - ./backend:/app/backend
      - ./frontend/build:/app/frontend/build
    environment:
      - ENVIRONMENT=development
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
    ports:
      - "8000:8000"
    
  # Optional: Add a frontend development service
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile
      target: frontend-builder
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    command: npm start
    depends_on:
      - backend