[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  "python -m ensurepip --upgrade",
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python backend/run_server.py"