[phases.setup]
aptPkgs = ["python3", "python3-dev", "python3-venv", "curl", "build-essential"]
nixPkgs = []

[phases.install]
cmds = [
    "curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
    "python3 get-pip.py",
    "pip3 install -r backend/requirements.txt"
]

[start]
cmd = "python3 backend/run_server.py"