[phases.setup]
nixPkgs = ["python39"]

[phases.install]
cmds = ["python -m pip install --upgrade pip setuptools wheel", "python -m pip install -r requirements.txt"]

[start]
cmd = "cd backend && python run_server.py"