[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.virtualenv"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip setuptools wheel",
    "python3 -m pip install -r backend/requirements.txt"
]

[start]
cmd = "python3 backend/run_server.py"