[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-dev", "python3-venv", "curl", "build-essential", "python3-setuptools", "python3-wheel"]
nixPkgs = []

[phases.install]
cmds = [
    "# Multiple fallback methods to ensure pip is available",
    "python3 -m ensurepip --upgrade || echo 'ensurepip failed, continuing...'",
    "curl -sSL https://bootstrap.pypa.io/get-pip.py -o get-pip.py || echo 'curl failed, continuing...'",
    "python3 get-pip.py || echo 'get-pip.py failed, continuing...'",
    "# Verify pip is available",
    "python3 -m pip --version || pip3 --version || pip --version",
    "# Install requirements using the most reliable pip method",
    "python3 -m pip install -r backend/requirements.txt || pip3 install -r backend/requirements.txt || pip install -r backend/requirements.txt"
]

[start]
cmd = "python3 backend/run_server.py"