[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
aptPkgs = ["python3-full", "python3-pip", "python3-dev", "build-essential"]
nixPkgs = []

[deploy]
startCommand = "python3 backend/run_server.py"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10