services:
  - type: web
    name: dr-kishan-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python run_server.py"
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: SUPABASE_URL
        value: https://demo-project.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.demo-key-for-testing
      - key: CORS_ORIGINS
        value: "*"
      - key: HIPAA_ENCRYPTION_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_HOSTS
        value: "*"